-- LifeOS Migration 0031: Global Food Library Seed
--
-- Redesign Nutrition spec, Section 4/5/6 — the American food library
-- (proteins/whole grains/vegetables/fruits/nuts & seeds) plus
-- individual Senegalese food items (complementing the already-seeded
-- Senegalese meals from migration 0027 — no existing meal data is
-- touched here) and 10 common American meals. Also seeds 3 example
-- rows (fresh grilled / deep-fried / heavily salted fish) directly
-- demonstrating Section 6's "the same food may have a different
-- classification depending on preparation" rule.
--
-- Nutrition figures are general estimates for the stated serving size
-- (documented the same way as meals.calories_kcal etc. — never
-- presented as lab-measured). Idempotent: only inserts a food/meal
-- whose (name_en, cuisine) or name_en doesn't already exist, same
-- WHERE NOT EXISTS pattern as migration 0027 (never ON CONFLICT — see
-- the migration 0024 42P10 postmortem earlier in this project).

insert into foods (name_en, name_fr, common_names, cuisine, country_region, category, serving_size_en, serving_size_fr, calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, added_sugar_g, sodium_mg, saturated_fat_g, preparation_method_en, preparation_method_fr, health_tags, classification, classification_reason_en, classification_reason_fr)
select v.name_en, v.name_fr, v.common_names, v.cuisine, v.country_region, v.category, v.serving_size_en, v.serving_size_fr, v.calories_kcal, v.protein_g, v.carbs_g, v.fat_g, v.fiber_g, v.sugar_g, v.added_sugar_g, v.sodium_mg, v.saturated_fat_g, v.preparation_method_en, v.preparation_method_fr, v.health_tags, v.classification, v.classification_reason_en, v.classification_reason_fr
from (
  values
  ('Salmon', 'Saumon', array[]::text[], 'american', 'United States', 'proteins', '3 oz cooked (85 g)', '85 g cuit', 175, 19, 0, 11, 0, 0, 0, 50, 2.5, null, null, array['high_protein', 'unsaturated_fat'], 'prioritize', null, null),
  ('Tuna', 'Thon', array[]::text[], 'american', 'United States', 'proteins', '3 oz cooked (85 g)', '85 g cuit', 110, 25, 0, 1, 0, 0, 0, 40, 0.3, null, null, array['high_protein', 'low_fat'], 'prioritize', null, null),
  ('Trout', 'Truite', array[]::text[], 'american', 'United States', 'proteins', '3 oz cooked (85 g)', '85 g cuit', 160, 21, 0, 7, 0, 0, 0, 45, 1.8, null, null, array['high_protein', 'unsaturated_fat'], 'prioritize', null, null),
  ('Cod', 'Morue', array[]::text[], 'american', 'United States', 'proteins', '3 oz cooked (85 g)', '85 g cuit', 90, 20, 0, 1, 0, 0, 0, 65, 0.2, null, null, array['high_protein', 'low_fat'], 'prioritize', null, null),
  ('Chicken breast', 'Blanc de poulet', array[]::text[], 'american', 'United States', 'proteins', '3 oz cooked (85 g)', '85 g cuit', 140, 26, 0, 3, 0, 0, 0, 60, 0.9, null, null, array['high_protein', 'low_fat'], 'prioritize', null, null),
  ('Turkey', 'Dinde', array[]::text[], 'american', 'United States', 'proteins', '3 oz cooked (85 g)', '85 g cuit', 135, 25, 0, 3, 0, 0, 0, 55, 1, null, null, array['high_protein', 'low_fat'], 'prioritize', null, null),
  ('Eggs', 'Œufs', array[]::text[], 'american', 'United States', 'proteins', '1 large egg (50 g)', '1 gros œuf (50 g)', 70, 6, 0.5, 5, 0, 0, 0, 65, 1.6, null, null, array['high_protein'], 'prioritize', null, null),
  ('Beans', 'Haricots', array[]::text[], 'american', 'United States', 'proteins', '1/2 cup cooked (85 g)', '125 mL cuits', 115, 7, 20, 0.5, 7, 0, 0, 5, 0.1, null, null, array['high_fiber', 'high_protein'], 'prioritize', null, null),
  ('Lentils', 'Lentilles', array[]::text[], 'american', 'United States', 'proteins', '1/2 cup cooked (100 g)', '125 mL cuites', 115, 9, 20, 0.4, 8, 1.5, 0, 2, 0.1, null, null, array['high_fiber', 'high_protein'], 'prioritize', null, null),
  ('Chickpeas', 'Pois chiches', array[]::text[], 'american', 'United States', 'proteins', '1/2 cup cooked (82 g)', '125 mL cuits', 135, 7, 22, 2, 6, 4, 0, 6, 0.2, null, null, array['high_fiber', 'high_protein'], 'prioritize', null, null),
  ('Lean beef', 'Bœuf maigre', array[]::text[], 'american', 'United States', 'proteins', '3 oz cooked (85 g)', '85 g cuit', 180, 24, 0, 9, 0, 0, 0, 55, 3.5, null, null, array['high_protein'], 'moderation', null, null),
  ('Oatmeal', 'Flocons d''avoine', array[]::text[], 'american', 'United States', 'whole_grains', '1/2 cup dry (40 g)', '40 g secs', 150, 5, 27, 3, 4, 1, 0, 0, 0.5, null, null, array['high_fiber', 'whole_grain'], 'prioritize', null, null),
  ('Brown rice', 'Riz brun', array[]::text[], 'american', 'United States', 'whole_grains', '1/2 cup cooked (98 g)', '125 mL cuit', 110, 2.5, 23, 1, 1.8, 0, 0, 5, 0.2, null, null, array['whole_grain'], 'prioritize', null, null),
  ('Quinoa', 'Quinoa', array[]::text[], 'american', 'United States', 'whole_grains', '1/2 cup cooked (93 g)', '125 mL cuit', 110, 4, 20, 2, 2.5, 0, 0, 5, 0.2, null, null, array['whole_grain', 'high_protein'], 'prioritize', null, null),
  ('Whole-wheat bread', 'Pain complet', array[]::text[], 'american', 'United States', 'whole_grains', '1 slice (28 g)', '1 tranche (28 g)', 80, 4, 14, 1, 2, 1.5, 1, 130, 0.2, null, null, array['whole_grain', 'high_fiber'], 'prioritize', null, null),
  ('Whole-grain pasta', 'Pâtes complètes', array[]::text[], 'american', 'United States', 'whole_grains', '1/2 cup cooked (70 g)', '125 mL cuites', 90, 4, 19, 0.5, 3, 0.5, 0, 0, 0.1, null, null, array['whole_grain', 'high_fiber'], 'prioritize', null, null),
  ('Barley', 'Orge', array[]::text[], 'american', 'United States', 'whole_grains', '1/2 cup cooked (79 g)', '125 mL cuit', 95, 2, 22, 0.3, 3, 0.2, 0, 2, 0.1, null, null, array['whole_grain', 'high_fiber'], 'prioritize', null, null),
  ('Whole-grain cereal', 'Céréales complètes', array[]::text[], 'american', 'United States', 'whole_grains', '3/4 cup (30 g)', '180 mL', 100, 3, 22, 1, 4, 5, 4, 140, 0.2, null, null, array['whole_grain'], 'moderation', null, null),
  ('Spinach', 'Épinards', array[]::text[], 'american', 'United States', 'vegetables', '1 cup raw (30 g)', '250 mL cru', 7, 1, 1, 0, 0.7, 0.1, 0, 24, 0, null, null, array['high_fiber', 'leafy_green'], 'prioritize', null, null),
  ('Broccoli', 'Brocoli', array[]::text[], 'american', 'United States', 'vegetables', '1 cup chopped (91 g)', '250 mL haché', 30, 2.5, 6, 0.3, 2.4, 1.5, 0, 30, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Cauliflower', 'Chou-fleur', array[]::text[], 'american', 'United States', 'vegetables', '1 cup chopped (100 g)', '250 mL haché', 25, 2, 5, 0.3, 2, 2, 0, 30, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Brussels sprouts', 'Choux de Bruxelles', array[]::text[], 'american', 'United States', 'vegetables', '1 cup (88 g)', '250 mL', 38, 3, 8, 0.3, 3, 2, 0, 22, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Carrots', 'Carottes', array[]::text[], 'american', 'United States', 'vegetables', '1 cup chopped (128 g)', '250 mL hachées', 52, 1, 12, 0.3, 3.6, 6, 0, 88, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Bell peppers', 'Poivrons', array[]::text[], 'american', 'United States', 'vegetables', '1 cup chopped (149 g)', '250 mL hachés', 30, 1, 7, 0.3, 2.5, 5, 0, 4, 0, null, null, array[]::text[], 'prioritize', null, null),
  ('Tomatoes', 'Tomates', array[]::text[], 'american', 'United States', 'vegetables', '1 medium (123 g)', '1 moyenne (123 g)', 22, 1, 5, 0.2, 1.5, 3, 0, 6, 0, null, null, array[]::text[], 'prioritize', null, null),
  ('Sweet potatoes', 'Patates douces', array[]::text[], 'american', 'United States', 'vegetables', '1 medium baked (114 g)', '1 moyenne cuite (114 g)', 100, 2, 24, 0.2, 4, 7, 0, 40, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Green beans', 'Haricots verts', array[]::text[], 'american', 'United States', 'vegetables', '1 cup (100 g)', '250 mL', 31, 2, 7, 0.2, 3, 3, 0, 6, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Kale', 'Chou frisé', array[]::text[], 'american', 'United States', 'vegetables', '1 cup chopped (67 g)', '250 mL haché', 33, 2.5, 6, 0.5, 1.3, 0, 0, 29, 0, null, null, array['leafy_green', 'high_fiber'], 'prioritize', null, null),
  ('Cabbage', 'Chou', array[]::text[], 'american', 'United States', 'vegetables', '1 cup chopped (89 g)', '250 mL haché', 22, 1, 5, 0.1, 2, 3, 0, 16, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Squash', 'Courge', array[]::text[], 'american', 'United States', 'vegetables', '1 cup cooked (205 g)', '250 mL cuite', 80, 2, 21, 0.2, 6, 4, 0, 6, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Avocado', 'Avocat', array[]::text[], 'american', 'United States', 'vegetables', '1/2 medium (100 g)', '1/2 moyen (100 g)', 160, 2, 9, 15, 7, 0.7, 0, 7, 2.1, null, null, array['high_fiber', 'unsaturated_fat'], 'prioritize', null, null),
  ('Apples', 'Pommes', array[]::text[], 'american', 'United States', 'fruits', '1 medium (182 g)', '1 moyenne (182 g)', 95, 0.5, 25, 0.3, 4, 19, 0, 2, 0, null, null, array['high_fiber', 'whole_fruit'], 'prioritize', null, null),
  ('Oranges', 'Oranges', array[]::text[], 'american', 'United States', 'fruits', '1 medium (131 g)', '1 moyenne (131 g)', 62, 1, 15, 0.2, 3, 12, 0, 0, 0, null, null, array['high_fiber', 'whole_fruit'], 'prioritize', null, null),
  ('Blueberries', 'Myrtilles', array[]::text[], 'american', 'United States', 'fruits', '1 cup (148 g)', '250 mL', 85, 1, 21, 0.5, 3.6, 15, 0, 1, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Strawberries', 'Fraises', array[]::text[], 'american', 'United States', 'fruits', '1 cup (152 g)', '250 mL', 49, 1, 12, 0.5, 3, 7, 0, 2, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Blackberries', 'Mûres', array[]::text[], 'american', 'United States', 'fruits', '1 cup (144 g)', '250 mL', 62, 2, 14, 0.7, 8, 7, 0, 1, 0, null, null, array['high_fiber', 'whole_fruit'], 'prioritize', null, null),
  ('Grapes', 'Raisins', array[]::text[], 'american', 'United States', 'fruits', '1 cup (151 g)', '250 mL', 104, 1, 27, 0.2, 1.4, 23, 0, 3, 0, null, null, array['whole_fruit'], 'moderation', null, null),
  ('Peaches', 'Pêches', array[]::text[], 'american', 'United States', 'fruits', '1 medium (150 g)', '1 moyenne (150 g)', 58, 1, 14, 0.4, 2, 13, 0, 0, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Pears', 'Poires', array[]::text[], 'american', 'United States', 'fruits', '1 medium (178 g)', '1 moyenne (178 g)', 100, 0.6, 27, 0.2, 5.5, 17, 0, 2, 0, null, null, array['high_fiber', 'whole_fruit'], 'prioritize', null, null),
  ('Bananas', 'Bananes', array[]::text[], 'american', 'United States', 'fruits', '1 medium (118 g)', '1 moyenne (118 g)', 105, 1.3, 27, 0.4, 3, 14, 0, 1, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Watermelon', 'Pastèque', array[]::text[], 'american', 'United States', 'fruits', '1 cup diced (152 g)', '250 mL en cubes', 46, 1, 11.5, 0.2, 0.6, 9.5, 0, 2, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Cantaloupe', 'Cantaloup', array[]::text[], 'american', 'United States', 'fruits', '1 cup diced (160 g)', '250 mL en cubes', 54, 1.3, 13, 0.3, 1.4, 13, 0, 26, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Almonds', 'Amandes', array[]::text[], 'american', 'United States', 'nuts_seeds', '1 oz / ~23 nuts (28 g)', '28 g (~23 amandes)', 160, 6, 6, 14, 3.5, 1, 0, 0, 1.1, null, null, array['unsaturated_fat', 'high_fiber'], 'prioritize', null, null),
  ('Walnuts', 'Noix', array[]::text[], 'american', 'United States', 'nuts_seeds', '1 oz / ~14 halves (28 g)', '28 g (~14 cerneaux)', 185, 4, 4, 18, 2, 0.7, 0, 1, 1.7, null, null, array['unsaturated_fat'], 'prioritize', null, null),
  ('Pistachios', 'Pistaches', array[]::text[], 'american', 'United States', 'nuts_seeds', '1 oz / ~49 nuts (28 g)', '28 g (~49 pistaches)', 160, 6, 8, 13, 3, 2, 0, 0, 1.6, null, null, array['unsaturated_fat', 'high_fiber'], 'prioritize', null, null),
  ('Peanuts', 'Arachides', array[]::text[], 'american', 'United States', 'nuts_seeds', '1 oz (28 g)', '28 g', 160, 7, 5, 14, 2.4, 1, 0, 5, 2, null, null, array['unsaturated_fat', 'high_protein'], 'prioritize', null, null),
  ('Cashews', 'Noix de cajou', array[]::text[], 'american', 'United States', 'nuts_seeds', '1 oz / ~18 nuts (28 g)', '28 g (~18 noix)', 155, 5, 9, 12, 1, 2, 0, 3, 2.2, null, null, array['unsaturated_fat'], 'prioritize', null, null),
  ('Chia seeds', 'Graines de chia', array[]::text[], 'american', 'United States', 'nuts_seeds', '1 oz (28 g)', '28 g', 137, 4.4, 12, 8.6, 10, 0, 0, 5, 0.9, null, null, array['high_fiber', 'unsaturated_fat'], 'prioritize', null, null),
  ('Flaxseed', 'Graines de lin', array[]::text[], 'american', 'United States', 'nuts_seeds', '1 tbsp ground (7 g)', '15 mL moulu', 37, 1.3, 2, 3, 1.9, 0.2, 0, 2, 0.3, null, null, array['high_fiber', 'unsaturated_fat'], 'prioritize', null, null),
  ('Pumpkin seeds', 'Graines de courge', array[]::text[], 'american', 'United States', 'nuts_seeds', '1 oz (28 g)', '28 g', 150, 7, 5, 13, 1.7, 0.4, 0, 5, 2.3, null, null, array['high_protein', 'unsaturated_fat'], 'prioritize', null, null),
  ('Sunflower seeds', 'Graines de tournesol', array[]::text[], 'american', 'United States', 'nuts_seeds', '1 oz (28 g)', '28 g', 165, 5.5, 6, 14, 3, 0.7, 0, 1, 1.5, null, null, array['unsaturated_fat', 'high_fiber'], 'prioritize', null, null),
  ('Millet', 'Mil', array[]::text[], 'senegalese_west_african', 'Senegal', 'whole_grains', '1/2 cup cooked (100 g)', '125 mL cuit', 105, 3, 21, 1, 1.5, 0, 0, 2, 0.1, null, null, array['whole_grain'], 'prioritize', null, null),
  ('Fonio', 'Fonio', array[]::text[], 'senegalese_west_african', 'Senegal', 'whole_grains', '1/2 cup cooked (90 g)', '125 mL cuit', 100, 2.5, 22, 0.5, 1.5, 0, 0, 1, 0.1, null, null, array['whole_grain'], 'prioritize', null, null),
  ('Niébé (black-eyed peas)', 'Niébé', array[]::text[], 'senegalese_west_african', 'Senegal', 'legumes', '1/2 cup cooked (85 g)', '125 mL cuit', 100, 7, 18, 0.5, 5.6, 3, 0, 3, 0.1, null, null, array['high_fiber', 'high_protein'], 'prioritize', null, null),
  ('Peanuts', 'Arachides', array[]::text[], 'senegalese_west_african', 'Senegal', 'nuts_seeds', '1 oz (28 g)', '28 g', 160, 7, 5, 14, 2.4, 1, 0, 5, 2, null, null, array['unsaturated_fat', 'high_protein'], 'prioritize', null, null),
  ('Cashews', 'Noix de cajou', array[]::text[], 'senegalese_west_african', 'Senegal', 'nuts_seeds', '1 oz / ~18 nuts (28 g)', '28 g (~18 noix)', 155, 5, 9, 12, 1, 2, 0, 3, 2.2, null, null, array['unsaturated_fat'], 'prioritize', null, null),
  ('Sesame seeds', 'Graines de sésame', array[]::text[], 'senegalese_west_african', 'Senegal', 'nuts_seeds', '1 tbsp (9 g)', '15 mL', 52, 1.6, 2, 4.5, 1.1, 0, 0, 1, 0.6, null, null, array['unsaturated_fat'], 'prioritize', null, null),
  ('Fish', 'Poisson', array[]::text[], 'senegalese_west_african', 'Senegal', 'proteins', '3 oz cooked (85 g)', '85 g cuit', 140, 22, 0, 5, 0, 0, 0, 60, 1.2, null, null, array['high_protein', 'unsaturated_fat'], 'prioritize', null, null),
  ('Sweet potato', 'Patate douce', array[]::text[], 'senegalese_west_african', 'Senegal', 'vegetables', '1 medium baked (114 g)', '1 moyenne cuite (114 g)', 100, 2, 24, 0.2, 4, 7, 0, 40, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Cassava', 'Manioc', array[]::text[], 'senegalese_west_african', 'Senegal', 'vegetables', '1/2 cup cooked (103 g)', '125 mL cuit', 110, 1, 26, 0.2, 1.3, 1.5, 0, 9, 0, null, null, array[]::text[], 'prioritize', null, null),
  ('Okra', 'Gombo', array[]::text[], 'senegalese_west_african', 'Senegal', 'vegetables', '1 cup (100 g)', '250 mL', 33, 2, 7, 0.2, 3.2, 1.5, 0, 7, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Eggplant', 'Aubergine', array[]::text[], 'senegalese_west_african', 'Senegal', 'vegetables', '1 cup cubed (82 g)', '250 mL en cubes', 20, 1, 5, 0.2, 2.5, 3, 0, 2, 0, null, null, array['high_fiber'], 'prioritize', null, null),
  ('Mango', 'Mangue', array[]::text[], 'senegalese_west_african', 'Senegal', 'fruits', '1 cup sliced (165 g)', '250 mL en tranches', 99, 1.4, 25, 0.6, 2.6, 23, 0, 2, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Papaya', 'Papaye', array[]::text[], 'senegalese_west_african', 'Senegal', 'fruits', '1 cup cubed (145 g)', '250 mL en cubes', 62, 0.7, 16, 0.2, 2.5, 11, 0, 5, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Guava', 'Goyave', array[]::text[], 'senegalese_west_african', 'Senegal', 'fruits', '1 medium (55 g)', '1 moyenne (55 g)', 37, 1.4, 8, 0.5, 3, 5, 0, 1, 0, null, null, array['high_fiber', 'whole_fruit'], 'prioritize', null, null),
  ('Watermelon', 'Pastèque', array[]::text[], 'senegalese_west_african', 'Senegal', 'fruits', '1 cup diced (152 g)', '250 mL en cubes', 46, 1, 11.5, 0.2, 0.6, 9.5, 0, 2, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Avocado', 'Avocat', array[]::text[], 'senegalese_west_african', 'Senegal', 'vegetables', '1/2 medium (100 g)', '1/2 moyen (100 g)', 160, 2, 9, 15, 7, 0.7, 0, 7, 2.1, null, null, array['high_fiber', 'unsaturated_fat'], 'prioritize', null, null),
  ('Baobab fruit (bouye)', 'Fruit du baobab (bouye)', array['bouye', 'bouy'], 'senegalese_west_african', 'Senegal', 'fruits', '2 tbsp pulp (15 g)', '30 mL de pulpe', 40, 0.5, 10, 0.1, 4.5, 3, 0, 3, 0, null, null, array['high_fiber', 'whole_fruit'], 'prioritize', null, null),
  ('Madd', 'Madd', array[]::text[], 'senegalese_west_african', 'Senegal', 'fruits', '~3 fruits (30 g)', '~3 fruits (30 g)', 35, 0.4, 9, 0.2, 1.5, 6, 0, 3, 0, null, null, array['whole_fruit'], 'prioritize', null, null),
  ('Fish (fresh, grilled)', 'Poisson (frais, grillé)', array[]::text[], 'other', null, 'proteins', '3 oz cooked (85 g)', '85 g cuit', 140, 22, 0, 5, 0, 0, 0, 60, 1.2, 'Grilled with little to no added oil or salt.', 'Grillé avec peu ou pas d''huile ni de sel ajoutés.', array['high_protein', 'unsaturated_fat'], 'prioritize', 'Fresh grilled fish is a lean protein source, generally low in sodium and saturated fat.', 'Le poisson frais grillé est une source de protéines maigres, généralement faible en sodium et en graisses saturées.'),
  ('Fish (deep-fried)', 'Poisson (frit)', array[]::text[], 'other', null, 'proteins', '3 oz cooked (85 g)', '85 g cuit', 230, 16, 8, 15, 0.3, 0, 0, 250, 3, 'Battered and deep-fried in oil.', 'Pané et frit dans l''huile.', array[]::text[], 'moderation', 'The batter and frying oil add calories and fat compared to grilling — fine to enjoy sometimes.', 'La panure et l''huile de friture ajoutent des calories et des graisses par rapport à la cuisson grillée — à apprécier de temps en temps.'),
  ('Fish (heavily salted/dried)', 'Poisson (très salé/séché)', array[]::text[], 'other', null, 'proteins', '1 oz (28 g)', '28 g', 80, 15, 0, 1, 0, 0, 0, 780, 0.2, 'Heavily salted and dried for preservation.', 'Fortement salé et séché pour la conservation.', array['high_sodium'], 'limit', 'Heavily salted or dried fish is high in sodium — have it less often, or rinse before cooking to reduce salt.', 'Le poisson très salé ou séché est riche en sodium — à consommer moins souvent, ou à rincer avant la cuisson pour réduire le sel.')
) as v(name_en, name_fr, common_names, cuisine, country_region, category, serving_size_en, serving_size_fr, calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, added_sugar_g, sodium_mg, saturated_fat_g, preparation_method_en, preparation_method_fr, health_tags, classification, classification_reason_en, classification_reason_fr)
where not exists (
  select 1 from foods existing where existing.name_en = v.name_en and existing.cuisine = v.cuisine
);

-- American meals (Section 4's "Common American Meals" list).
insert into meals (name_en, name_fr, description_en, description_fr, cuisine, meal_type, serving_size_en, serving_size_fr, ingredients, preparation_en, preparation_fr, calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg, rating, rating_reason_en, rating_reason_fr, tags)
select v.name_en, v.name_fr, v.description_en, v.description_fr, v.cuisine, v.meal_type, v.serving_size_en, v.serving_size_fr, v.ingredients, v.preparation_en, v.preparation_fr, v.calories_kcal, v.protein_g, v.carbs_g, v.fat_g, v.fiber_g, v.sugar_g, v.sodium_mg, v.rating, v.rating_reason_en, v.rating_reason_fr, v.tags
from (
  values
  ('Oatmeal with Berries and Walnuts', 'Flocons d''avoine aux baies et aux noix', 'A warm bowl of oatmeal topped with fresh berries and walnuts.', 'Un bol de flocons d''avoine chaud garni de baies fraîches et de noix.', 'american', 'breakfast', '1 bowl', '1 bol', jsonb_build_array(jsonb_build_object('en', 'Oatmeal', 'fr', 'Flocons d''avoine'), jsonb_build_object('en', 'Mixed berries', 'fr', 'Baies mélangées'), jsonb_build_object('en', 'Walnuts', 'fr', 'Noix'), jsonb_build_object('en', 'Cinnamon (optional)', 'fr', 'Cannelle (facultatif)')), 'Cook oatmeal with water or milk, top with berries and chopped walnuts.', 'Cuire les flocons d''avoine dans de l''eau ou du lait, garnir de baies et de noix hachées.', 340, 10, 48, 14, 8, 12, 20, 'best_choice', 'High in fiber and unsaturated fat, with no added sugar needed.', 'Riche en fibres et en graisses insaturées, sans besoin de sucre ajouté.', array['high_fiber', 'unsaturated_fat']),
  ('Grilled Salmon with Brown Rice and Broccoli', 'Saumon grillé, riz brun et brocoli', 'Grilled salmon served with brown rice and steamed broccoli.', 'Saumon grillé servi avec du riz brun et du brocoli vapeur.', 'american', 'dinner', '1 plate', '1 assiette', jsonb_build_array(jsonb_build_object('en', 'Salmon', 'fr', 'Saumon'), jsonb_build_object('en', 'Brown rice', 'fr', 'Riz brun'), jsonb_build_object('en', 'Broccoli', 'fr', 'Brocoli'), jsonb_build_object('en', 'Olive oil', 'fr', 'Huile d''olive'), jsonb_build_object('en', 'Lemon', 'fr', 'Citron')), 'Grill the salmon with a little olive oil and lemon, serve with brown rice and steamed broccoli.', 'Griller le saumon avec un peu d''huile d''olive et de citron, servir avec du riz brun et du brocoli vapeur.', 480, 34, 45, 16, 6, 3, 180, 'best_choice', 'Lean protein, whole grains, and vegetables in one balanced plate.', 'Protéines maigres, céréales complètes et légumes dans une assiette équilibrée.', array['fish', 'whole_grain', 'high_fiber']),
  ('Chicken and Quinoa Bowl', 'Bol de poulet et quinoa', 'Grilled chicken over quinoa with mixed vegetables.', 'Poulet grillé sur lit de quinoa avec légumes mélangés.', 'american', 'lunch', '1 bowl', '1 bol', jsonb_build_array(jsonb_build_object('en', 'Chicken breast', 'fr', 'Blanc de poulet'), jsonb_build_object('en', 'Quinoa', 'fr', 'Quinoa'), jsonb_build_object('en', 'Bell peppers', 'fr', 'Poivrons'), jsonb_build_object('en', 'Spinach', 'fr', 'Épinards'), jsonb_build_object('en', 'Olive oil', 'fr', 'Huile d''olive')), 'Grill the chicken, combine with cooked quinoa and sautéed vegetables.', 'Griller le poulet, combiner avec le quinoa cuit et les légumes sautés.', 420, 36, 38, 12, 6, 4, 220, 'best_choice', 'A balanced combination of lean protein, whole grain, and vegetables.', 'Une combinaison équilibrée de protéines maigres, de céréales complètes et de légumes.', array['chicken', 'whole_grain', 'high_protein']),
  ('Turkey Whole-Grain Sandwich', 'Sandwich à la dinde sur pain complet', 'A simple turkey sandwich on whole-grain bread with vegetables.', 'Un sandwich simple à la dinde sur pain complet avec des légumes.', 'american', 'lunch', '1 sandwich', '1 sandwich', jsonb_build_array(jsonb_build_object('en', 'Turkey', 'fr', 'Dinde'), jsonb_build_object('en', 'Whole-wheat bread', 'fr', 'Pain complet'), jsonb_build_object('en', 'Lettuce', 'fr', 'Laitue'), jsonb_build_object('en', 'Tomato', 'fr', 'Tomate'), jsonb_build_object('en', 'Mustard', 'fr', 'Moutarde')), 'Layer turkey, lettuce, and tomato between two slices of whole-grain bread.', 'Empiler la dinde, la laitue et la tomate entre deux tranches de pain complet.', 320, 26, 34, 8, 5, 5, 620, 'good_choice', 'A practical lean-protein option — consider a lower-sodium deli turkey or bread when available.', 'Une option pratique de protéines maigres — envisagez une dinde ou un pain moins salés si possible.', array['turkey', 'whole_grain']),
  ('Lentil Soup', 'Soupe de lentilles', 'A hearty lentil soup with vegetables.', 'Une soupe de lentilles consistante avec des légumes.', 'american', 'lunch', '1 bowl', '1 bol', jsonb_build_array(jsonb_build_object('en', 'Lentils', 'fr', 'Lentilles'), jsonb_build_object('en', 'Carrots', 'fr', 'Carottes'), jsonb_build_object('en', 'Celery', 'fr', 'Céleri'), jsonb_build_object('en', 'Onion', 'fr', 'Oignon'), jsonb_build_object('en', 'Vegetable broth', 'fr', 'Bouillon de légumes')), 'Simmer lentils with chopped vegetables and low-sodium broth until tender.', 'Laisser mijoter les lentilles avec les légumes hachés et un bouillon faible en sodium jusqu''à tendreté.', 230, 14, 38, 1, 12, 5, 480, 'best_choice', 'High in fiber and plant protein — choose a low-sodium broth to keep sodium moderate.', 'Riche en fibres et en protéines végétales — choisissez un bouillon faible en sodium.', array['legume', 'high_fiber']),
  ('Bean and Vegetable Bowl', 'Bol de haricots et légumes', 'A simple bowl of beans and roasted vegetables.', 'Un bol simple de haricots et de légumes rôtis.', 'american', 'dinner', '1 bowl', '1 bol', jsonb_build_array(jsonb_build_object('en', 'Beans', 'fr', 'Haricots'), jsonb_build_object('en', 'Sweet potatoes', 'fr', 'Patates douces'), jsonb_build_object('en', 'Kale', 'fr', 'Chou frisé'), jsonb_build_object('en', 'Olive oil', 'fr', 'Huile d''olive')), 'Roast the sweet potato and kale, combine with warmed beans.', 'Rôtir la patate douce et le chou frisé, combiner avec les haricots réchauffés.', 360, 13, 55, 10, 14, 9, 140, 'best_choice', 'Plant-forward, high in fiber, and naturally low in sodium.', 'À dominante végétale, riche en fibres et naturellement faible en sodium.', array['legume', 'high_fiber']),
  ('Baked Sweet Potato with Salmon', 'Patate douce cuite au four avec saumon', 'A baked sweet potato served alongside grilled salmon.', 'Une patate douce cuite au four accompagnée de saumon grillé.', 'american', 'dinner', '1 plate', '1 assiette', jsonb_build_array(jsonb_build_object('en', 'Sweet potatoes', 'fr', 'Patates douces'), jsonb_build_object('en', 'Salmon', 'fr', 'Saumon'), jsonb_build_object('en', 'Green beans', 'fr', 'Haricots verts')), 'Bake the sweet potato, grill the salmon, and steam the green beans.', 'Cuire la patate douce au four, griller le saumon et cuire les haricots verts à la vapeur.', 410, 28, 40, 14, 7, 10, 110, 'best_choice', 'A balanced plate combining lean protein, fiber, and unsaturated fat.', 'Une assiette équilibrée combinant protéines maigres, fibres et graisses insaturées.', array['fish', 'high_fiber']),
  ('Greek Yogurt with Berries and Nuts', 'Yaourt grec aux baies et aux noix', 'Plain Greek yogurt topped with fresh berries and a small handful of nuts.', 'Yaourt grec nature garni de baies fraîches et d''une petite poignée de noix.', 'american', 'snack', '1 cup', '250 mL', jsonb_build_array(jsonb_build_object('en', 'Plain Greek yogurt', 'fr', 'Yaourt grec nature'), jsonb_build_object('en', 'Mixed berries', 'fr', 'Baies mélangées'), jsonb_build_object('en', 'Almonds', 'fr', 'Amandes')), 'Top plain Greek yogurt with berries and chopped almonds.', 'Garnir le yaourt grec nature de baies et d''amandes hachées.', 220, 18, 20, 8, 4, 14, 65, 'best_choice', 'High in protein with no added sugar when using plain yogurt.', 'Riche en protéines, sans sucre ajouté si le yaourt nature est utilisé.', array['high_protein', 'dairy']),
  ('Vegetable Omelet with Whole-Grain Toast', 'Omelette aux légumes et pain complet grillé', 'An omelet with mixed vegetables served with whole-grain toast.', 'Une omelette aux légumes mélangés servie avec du pain complet grillé.', 'american', 'breakfast', '1 plate', '1 assiette', jsonb_build_array(jsonb_build_object('en', 'Eggs', 'fr', 'Œufs'), jsonb_build_object('en', 'Spinach', 'fr', 'Épinards'), jsonb_build_object('en', 'Bell peppers', 'fr', 'Poivrons'), jsonb_build_object('en', 'Whole-wheat bread', 'fr', 'Pain complet')), 'Whisk eggs with chopped vegetables, cook in a lightly oiled pan, serve with toast.', 'Battre les œufs avec les légumes hachés, cuire dans une poêle légèrement huilée, servir avec le pain grillé.', 320, 20, 26, 15, 5, 4, 340, 'best_choice', 'A protein- and vegetable-forward breakfast with whole grains.', 'Un petit-déjeuner riche en protéines et en légumes, avec des céréales complètes.', array['eggs', 'whole_grain']),
  ('Chicken and Avocado Salad', 'Salade de poulet et avocat', 'Grilled chicken and avocado over mixed greens.', 'Poulet grillé et avocat sur un mélange de jeunes pousses.', 'american', 'lunch', '1 bowl', '1 bol', jsonb_build_array(jsonb_build_object('en', 'Chicken breast', 'fr', 'Blanc de poulet'), jsonb_build_object('en', 'Avocado', 'fr', 'Avocat'), jsonb_build_object('en', 'Mixed greens', 'fr', 'Jeunes pousses mélangées'), jsonb_build_object('en', 'Tomatoes', 'fr', 'Tomates'), jsonb_build_object('en', 'Olive oil and lemon dressing', 'fr', 'Vinaigrette huile d''olive et citron')), 'Toss grilled chicken, sliced avocado, and vegetables with a light olive oil and lemon dressing.', 'Mélanger le poulet grillé, l''avocat tranché et les légumes avec une vinaigrette légère à l''huile d''olive et au citron.', 390, 32, 14, 24, 8, 4, 190, 'best_choice', 'Lean protein with fiber and unsaturated fat from avocado and olive oil.', 'Protéines maigres avec des fibres et des graisses insaturées provenant de l''avocat et de l''huile d''olive.', array['chicken', 'high_fiber', 'unsaturated_fat'])
) as v(name_en, name_fr, description_en, description_fr, cuisine, meal_type, serving_size_en, serving_size_fr, ingredients, preparation_en, preparation_fr, calories_kcal, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg, rating, rating_reason_en, rating_reason_fr, tags)
where not exists (
  select 1 from meals existing where existing.name_en = v.name_en
);

notify pgrst, 'reload schema';
